### ISSUE TITLE
Rate command repeating numbers very frequently.

### ISSUE THREAD

**Issue by peter765** [Dynista/pineapple#39]
https://discordapp.com/channels/234859925342388235/241358991005974538/738572215930454057 (see thread)

Issue first appeared on May 20, 2020

The following numbers consistently appear: 
98.02
78.62
51.66

**Comment by nQuisition** [comment]
Not 100% on Python imports, but if `import random` imports a singleton, then I think it is because of https://github.com/Dynista/pineapple/blob/develop/ClientWrapper.py#L23 , so it sets a seed each time an embed is sent based on the sending plugin name. So the "random" number you get is determined solely by which plugin has sent the last message. That explains why you get the same number multiple times in a row - the seed is reset to the same value every time you call the `rate` command
